name: Semantic Release

on:
  push:
    branches:
      - main
      - release/**

jobs:
  bump-version:
    if: ${{ ! endsWith(github.event.head_commit.message, '[release]') }}
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.8.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_email: "engineering@climate-x.com"
          git_committer_name: "climatex-engineering"

      - name: Send Slack Notification
        if: steps.release.outputs.released == 'true'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL }}
        run: |
          MSG="${{ github.event.head_commit.message }}"
          if [[ "$MSG" == *"feat:"* ]] || [[ "$MSG" == *"feat("* ]] || [[ "$MSG" == *"!"* ]] || [[ "$MSG" == *"BREAKING CHANGE"* ]]; then
             if [ -n "$SLACK_WEBHOOK_URL" ]; then
                PAYLOAD=$(jq -n \
                  --arg title "🚀 *New Release Published:* v${{ steps.release.outputs.version }}" \
                  --arg url "https://github.com/${{ github.repository }}/releases/tag/v${{ steps.release.outputs.version }}" \
                  '{"text": "\($title)\nView Release: \($url)"}')
                curl -s -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
             else
                echo "SLACK_WEBHOOK_URL secret not set. Skipping Slack notification."
             fi
          else
             echo "Skipping Slack notification for patch/fix release."
          fi

      - name: Notify Slack on failure
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          notification_title: "{emoji} *{workflow}* {status_message}"
          message_format: "*User :* ${{ github.actor }}\n*Event:* ${{ github.event_name }}\n*Source Branch:* ${{ env.CI_ACTION_REF_NAME }}\n*Target Branch (If available):* ${{ github.base_ref }}\n*Pull Request URL (If available):* <{repo_url}/pull/${{ github.event.number }}|View Pull Request>\n*Workflow URL:* <{run_url}|View Workflow>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL }}
